/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 https://docusaurus.io/zh-CN/docs/sidebar#understanding-sidebar-items
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  cassandraSidebar: [{ type: 'autogenerated', dirName: 'database/cassandra' }],
  mysqlSidebar: [{ type: 'autogenerated', dirName: 'database/mysql' }],
  redisSidebar: [{ type: 'autogenerated', dirName: 'database/redis' }],
  tidbSidebar: [{ type: 'autogenerated', dirName: 'database/tidb' }],

  linuxSidebar: [{ type: 'autogenerated', dirName: 'devops/linux' }],
  dockerSidebar: [{ type: 'autogenerated', dirName: 'devops/docker' }],
  cicdSidebar: [{ type: 'autogenerated', dirName: 'devops/ci' }, { type: 'autogenerated', dirName: 'devops/cd' }],
  k8sSidebar: [{ type: 'autogenerated', dirName: 'devops/k8s' }],
  testSidebar: [{ type: 'autogenerated', dirName: 'devops/test' }],

  algorithmSidebar: [{ type: 'autogenerated', dirName: 'general/algorithm' }],
  dataStructureSidebar: [{ type: 'autogenerated', dirName: 'general/data-structure' }],
  dddSidebar: [{ type: 'autogenerated', dirName: 'general/ddd' }],
  designPatternSidebar: [{ type: 'autogenerated', dirName: 'general/design-pattern' }],
  gitSidebar: [{ type: 'autogenerated', dirName: 'general/git' }],
  umlSidebar: [{ type: 'autogenerated', dirName: 'general/uml' }],
  networkSidebar: [{ type: 'autogenerated', dirName: 'general/network' }],

  javaSidebar: [{ type: 'autogenerated', dirName: 'java' }],

  aplloSidebar: [{ type: 'autogenerated', dirName: 'middleware/apllo' }],
  dubboSidebar: [{ type: 'autogenerated', dirName: 'middleware/dubbo' }],
  esSidebar: [{ type: 'autogenerated', dirName: 'middleware/es' }],
  kafkaSidebar: [{ type: 'autogenerated', dirName: 'middleware/kafka' }],
  mqSidebar: [{ type: 'autogenerated', dirName: 'middleware/mq' }],
  nacosSidebar: [{ type: 'autogenerated', dirName: 'middleware/nacos' }],
  nettySidebar: [{ type: 'autogenerated', dirName: 'middleware/netty' }],
  sentinelSidebar: [{ type: 'autogenerated', dirName: 'middleware/sentinel' }],

  bootSidebar: [{ type: 'autogenerated', dirName: 'spring/boot' }],
  cloudSidebar: [{ type: 'autogenerated', dirName: 'spring/cloud' }],
  frameworkSidebar: [{ type: 'autogenerated', dirName: 'spring/framework' }],
  mvcSidebar: [{ type: 'autogenerated', dirName: 'spring/mvc' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
